### ISSUE TITLE
Write more unit tests

### ISSUE THREAD

**Issue by christianscott** [christianscott/curry.py#1]
I'm sure there are even more cases where this function fails in its' current form, it'd be great to find them!

**Comment by ben-e-whitney** [comment]
See #20.

**Comment by AtelesPaniscus** [comment]
So the brackets tests is not the kind of thing you want ?  Guess there is no point in submitting the other tests I wrote that should pass now you've merged @ben-e-whitney changes.

**Comment by christianscott** [comment]
@AtelesPaniscus if the tests you've written improve coverage then I'm happy to add them

**Comment by AtelesPaniscus** [comment]
Oh,  I see.  No thanks.
