### ISSUE TITLE
Wraps function

### ISSUE THREAD

**Issue by riquellopes** [christianscott/curry.py#10]
You could use the [wraps](https://docs.python.org/3.6/library/functools.html#functools.wraps) function, it already does everything you need when you are working with decorator.

```python
from functools import wraps

def curry(func):
   @wraps(func)
   def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper
```

**Comment by christianscott** [comment]
That's a great tip. Thanks so much! I fixed this in 278c781
