### ISSUE TITLE
Use default arguments

### ISSUE THREAD

**Issue by christianscott** [christianscott/curry.py#11]
Currently there's no way to use default arguments. For example:

```python
@curry
def add(a, b=10):
    return a + b

x = add(10) # sometimes will want this to be 20, but *always* returns another function
```

Will need to think of some way to specify that this is the behaviour we want. There are two ways that I can imagine:

* `@curry(use_default=True)` - less flexible, harder to implement
* `add(10, done=True)` - more flexible, easy to implement (I like this better)

**Comment by TechieBoy** [comment]
Hey, I would like to work on this.
What should happen if the user fails to specify a positional argument?

For example, consider:
```python
@curry
def add(a, b=10, c=30):
    return a + b + c

x = add(b=1)(c=20,done=True)
```
Should this raise an error or do we assume that the user meant:
```python
x = add(b=1)(c=20)
```
and simply return a function?

**Comment by christianscott** [comment]
For now, I think simply passing whatever arguments have been collected so far would be ok. Let python throw the error if they get something wrong!

Like this:
```
>>> ks = { 'foo': 1 }
>>> add(1)(**ks, done=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() got an unexpected keyword argument 'foo'
```

Or like this, if they miss an arg:
```
>>> add(b=2)(c=10, done=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add() missing 1 required keyword-only argument: 'a'
```

**Comment by praveensvsrk** [comment]
Suppose that `add` has a keyword argument `done`, then `add(10, done=True)` altogether means something else. 
**EDIT**: How about forcing evaluation with whatever arguments we have by calling it?

```python
@curry
def add(a, b=10):
    return a + b

x = add(10) # returns function
x = add(10)() # returns 20
```

**Comment by choudhary001** [comment]
Is this already assigned to someone? If not I would like to work on this issue

**Comment by christianscott** [comment]
Go right ahead, I'm still not sure how this should work though.
