### ISSUE TITLE
Add clear explanation of how the curry function works

### ISSUE THREAD

**Issue by christianscott** [christianscott/curry.py#12]
It would be nice if there was an explanation of how it works for new contributors. Particularly:
* Why are there two nested functions?
* Why is the `nonlocal` keyword being used?

Either via comments or in the README.

**Comment by praveensvsrk** [comment]
- Why are there two nested functions?   

  Let us decorate our add function first
  ```python
    @curry
    def add(a, b):
        return a + b
    ```
    Now, `add` evaluates to this (for a better understanding, I have removed wraps): 
    ```python
    >>> add
    <function curry.<locals>.curried_factory at 0x030EA978>
   ```
    The `curried_factory` function maintains the state of the function, i.e, it stores the arguments and keyword arguments. But we haven't called the function yet. So, let us start supplying arguments to the `add` function.
    ```python
   >>> add(1)
   <function curry.<locals>.curried_factory.<locals>.curried at 0x030F2930>
    ```
    We want to keep adding the arguments to the argument store, and execute the `add` function only when all the necessary arguments are accumulated. This is where the `curried` function comes into play. It contains the logic for adding arguments to the argument store and conditional execution of the function.
    ```python
    >>> add(1)(4)
    5
    ```
-  Why is the `nonlocal` keyword being used?

    We are referencing variables `args_store` and `kwargs_store` that are neither in the local scope or the global scope, but in the enclosing scope. `nonlocal` is the handy keyword that helps in referring to variables in the outer scope.

Am I missing something?

**Comment by Pradhvan** [comment]
@chrfrasco  Is this issue closed ? or can I pick it up.

**Comment by christianscott** [comment]
That would be great, we're in need of some updated documentation. It would be best to put it in the README rather than in the form of comments (despite what I said above)
