### ISSUE TITLE
Arguments persist between function calls

### ISSUE THREAD

**Issue by christianscott** [christianscott/curry.py#4]
The `args` object is created when the function is curried. That means that the arguments keep getting added each time the function is called, oops...

If we add a print statement to the `curried` function, this is what is printed out:
```
>>> add(1)(2)
[]
[1]
3
>>> add(1)(2)
[1, 2]
[1, 2, 1]
```

Thanks to @praveensvsrk for pointing this out!

**Comment by praveensvsrk** [comment]
Something like this will probably work. Subsequent `add()` calls will not refer to the same argument list anymore, a new curry object is created for each `add()` call

```
def curry(fun):
    arg_count = len(signature(fun).parameters)

    def curried(*args_store):
        def _inner(*args):
            new_args = args_store + args
            if len(new_args) == arg_count:
                return fun(*new_args)
            else:
                return _inner
        _inner.__name__ = fun.__name__
        return _inner
    return curried
```
![screenshot_7](https://user-images.githubusercontent.com/10628197/30963415-f81cdefa-a46a-11e7-8dac-3ff17dc24abd.png)

EDIT: This approach doesn't seem to work for 2+ arguments, I'll modify this when I come up with a fix.

**Comment by praveensvsrk** [comment]
#8 
Tweaked the code a bit and it works now. Opened a PR.
